esphome:
  name: "somfy-rts"
  name_add_mac_suffix: true
  platform: ESP32
  board: esp32dev
  libraries:
    - EEPROM
    - SPI
    - SmartRC-CC1101-Driver-Lib@2.5.6
    - Somfy_Remote_Lib@0.4.1
  includes:
    - somfy_cover.h

wifi:
  ap:
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:



web_server:
  port: 80

sensor:
  - platform: uptime
    name: Uptime Sensor\core_configurator

  - platform: wifi_signal
    name: "WiFi Signal Sensor"


cover:
  - platform: custom
    lambda: |-
      auto somfy_remote = new SomfyESPRemote();
      byte mac[6];
      uint32_t somfy_addr = 0;
      WiFi.macAddress(mac);
      somfy_addr = (mac[5] << 16) + (mac[4] << 8) + mac[3];
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+1);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+2);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+3);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+4);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+5);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+6);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+7);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+8);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+9);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+10);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+11);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+12);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+13);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+14);
      ESP_LOGD("somfy_addr", "Channel address: %06x", somfy_addr+15);
      somfy_remote->add_cover("somfy", "CH01", somfy_addr);
      somfy_remote->add_cover("somfy", "CH02", somfy_addr+1);
      somfy_remote->add_cover("somfy", "CH03", somfy_addr+2);
      somfy_remote->add_cover("somfy", "CH04", somfy_addr+3);
      somfy_remote->add_cover("somfy", "CH05", somfy_addr+4);
      somfy_remote->add_cover("somfy", "CH06", somfy_addr+5);
      somfy_remote->add_cover("somfy", "CH07", somfy_addr+6);
      somfy_remote->add_cover("somfy", "CH08", somfy_addr+7);
      somfy_remote->add_cover("somfy", "CH09", somfy_addr+8);
      somfy_remote->add_cover("somfy", "CH10", somfy_addr+9);
      somfy_remote->add_cover("somfy", "CH11", somfy_addr+10);
      somfy_remote->add_cover("somfy", "CH12", somfy_addr+11);
      somfy_remote->add_cover("somfy", "CH13", somfy_addr+12);
      somfy_remote->add_cover("somfy", "CH14", somfy_addr+13);
      somfy_remote->add_cover("somfy", "CH15", somfy_addr+14);
      somfy_remote->add_cover("somfy", "CH16", somfy_addr+15);
      App.register_component(somfy_remote);
      return somfy_remote->covers;

    covers:
      - id: "somfy1"
        name: "Somfy CH01"
      - id: "somfy2"
        name: "Somfy CH02"
      - id: "somfy3"
        name: "Somfy CH03"
      - id: "somfy4"
        name: "Somfy CH04"
      - id: "somfy5"
        name: "Somfy CH05"
      - id: "somfy6"
        name: "Somfy CH06"
      - id: "somfy7"
        name: "Somfy CH07"
      - id: "somfy8"
        name: "Somfy CH08"
      - id: "somfy9"
        name: "Somfy CH09"
      - id: "somfy10"
        name: "Somfy CH10"
      - id: "somfy11"
        name: "Somfy CH11"
      - id: "somfy12"
        name: "Somfy CH12"
      - id: "somfy13"
        name: "Somfy CH13"
      - id: "somfy14"
        name: "Somfy CH14"
      - id: "somfy15"
        name: "Somfy CH15"
      - id: "somfy16"
        name: "Somfy CH16"



button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
  - platform: template
    name: "PROG01"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy1))->program();
  - platform: template
    name: "PROG02"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy2))->program();
  - platform: template
    name: "PROG03"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy3))->program();
  - platform: template
    name: "PROG04"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy4))->program();
  - platform: template
    name: "PROG05"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy5))->program();
  - platform: template
    name: "PROG06"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy6))->program();
  - platform: template
    name: "PROG07"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy7))->program();
  - platform: template
    name: "PROG08"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy8))->program();
  - platform: template
    name: "PROG09"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy9))->program();
  - platform: template
    name: "PROG10"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy10))->program();
  - platform: template
    name: "PROG11"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy11))->program();
  - platform: template
    name: "PROG12"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy12))->program();
  - platform: template
    name: "PROG13"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy13))->program();
  - platform: template
    name: "PROG14"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy14))->program();
  - platform: template
    name: "PROG15"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy15))->program();
  - platform: template
    name: "PROG16"
    on_press:
      - lambda: |-
          ((SomfyESPCover*)id(somfy16))->program();
